apiVersion: v1
kind: Service
metadata:
   name: spring-boot-microservice
   labels: 
      name: spring-boot-microservice
spec:
   ports:
      - port: 8081
        targetPort: 8081
        protocol: TCP
   selector:
      app: spring-boot-microservice
   type: LoadBalancer
        
